export type ModelPrediction = {
  id: number;
  title: string;
  location: string;
  propertyType: string;
  listedPriceUsd: number;
  sizeSqm: number;
  pricePerSqm: number;
  predictedNegotiationReference: number;
  predictedNegotiationLow: number;
  predictedNegotiationHigh: number;
  predictedReviewCategory: "normal" | "medium-risk" | "suspicious";
};

export const modelPredictions: ModelPrediction[] = [
  {
    id: 1,
    title: "3+ YEARS ON JIJI",
    location: "Arada",
    propertyType: "Apartment",
    listedPriceUsd: 3158,
    sizeSqm: 100,
    pricePerSqm: 31,
    predictedNegotiationReference: 2801,
    predictedNegotiationLow: 2521,
    predictedNegotiationHigh: 2857,
    predictedReviewCategory: "normal",
  },
  {
    id: 2,
    title: "ETB 169,000 per month 4bdrm Apartment in Kazanchis, Kirkos for rent Modern, Luxury and Spa",
    location: "Kirkos",
    propertyType: "Apartment",
    listedPriceUsd: 2965,
    sizeSqm: 100,
    pricePerSqm: 29,
    predictedNegotiationReference: 2769,
    predictedNegotiationLow: 2492,
    predictedNegotiationHigh: 2824,
    predictedReviewCategory: "normal",
  },
  {
    id: 3,
    title: "3+ YEARS ON JIJI",
    location: "Bole",
    propertyType: "Property",
    listedPriceUsd: 5263,
    sizeSqm: 100,
    pricePerSqm: 52,
    predictedNegotiationReference: 4789,
    predictedNegotiationLow: 4310,
    predictedNegotiationHigh: 4885,
    predictedReviewCategory: "medium-risk",
  },
  {
    id: 4,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 4386,
    sizeSqm: 100,
    pricePerSqm: 43,
    predictedNegotiationReference: 3912,
    predictedNegotiationLow: 3521,
    predictedNegotiationHigh: 3990,
    predictedReviewCategory: "medium-risk",
  },
  {
    id: 5,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 1579,
    sizeSqm: 100,
    pricePerSqm: 15,
    predictedNegotiationReference: 1489,
    predictedNegotiationLow: 1340,
    predictedNegotiationHigh: 1519,
    predictedReviewCategory: "normal",
  },
  {
    id: 6,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 2632,
    sizeSqm: 100,
    pricePerSqm: 26,
    predictedNegotiationReference: 2361,
    predictedNegotiationLow: 2125,
    predictedNegotiationHigh: 2408,
    predictedReviewCategory: "normal",
  },
  {
    id: 7,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 1491,
    sizeSqm: 100,
    pricePerSqm: 14,
    predictedNegotiationReference: 1489,
    predictedNegotiationLow: 1340,
    predictedNegotiationHigh: 1519,
    predictedReviewCategory: "normal",
  },
  {
    id: 8,
    title: "3+ YEARS ON JIJI",
    location: "Yeka",
    propertyType: "Commercial",
    listedPriceUsd: 2281,
    sizeSqm: 180,
    pricePerSqm: 12,
    predictedNegotiationReference: 2179,
    predictedNegotiationLow: 1961,
    predictedNegotiationHigh: 2223,
    predictedReviewCategory: "normal",
  },
  {
    id: 9,
    title: "3+ YEARS ON JIJI",
    location: "Akaky Kaliti",
    propertyType: "Commercial",
    listedPriceUsd: 3860,
    sizeSqm: 250,
    pricePerSqm: 15,
    predictedNegotiationReference: 3965,
    predictedNegotiationLow: 3568,
    predictedNegotiationHigh: 4044,
    predictedReviewCategory: "normal",
  },
  {
    id: 10,
    title: "ETB 180,000 የሚከራይ መጋዘን አያት አከባቢ በቂ ቢሮ ጋር Warehouse for Rent in Ayat Addis Ababa Warshouse",
    location: "Yeka",
    propertyType: "Commercial",
    listedPriceUsd: 3158,
    sizeSqm: 6000,
    pricePerSqm: 0,
    predictedNegotiationReference: 2996,
    predictedNegotiationLow: 2696,
    predictedNegotiationHigh: 3056,
    predictedReviewCategory: "normal",
  },
  {
    id: 11,
    title: "ETB 175,000 Warehouse for Rent in Kaliti Aa Warehouse for rent Total area = 700 sq Warehou",
    location: "Akaky Kaliti",
    propertyType: "Commercial",
    listedPriceUsd: 3070,
    sizeSqm: 700,
    pricePerSqm: 4,
    predictedNegotiationReference: 2929,
    predictedNegotiationLow: 2636,
    predictedNegotiationHigh: 2988,
    predictedReviewCategory: "normal",
  },
  {
    id: 12,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 2105,
    sizeSqm: 100,
    pricePerSqm: 21,
    predictedNegotiationReference: 1793,
    predictedNegotiationLow: 1614,
    predictedNegotiationHigh: 1829,
    predictedReviewCategory: "normal",
  },
  {
    id: 13,
    title: "3+ YEARS ON JIJI",
    location: "Akaky Kaliti",
    propertyType: "Property",
    listedPriceUsd: 6667,
    sizeSqm: 100,
    pricePerSqm: 66,
    predictedNegotiationReference: 5573,
    predictedNegotiationLow: 5016,
    predictedNegotiationHigh: 5684,
    predictedReviewCategory: "medium-risk",
  },
  {
    id: 14,
    title: "3+ YEARS ON JIJI",
    location: "Bole",
    propertyType: "Property",
    listedPriceUsd: 5614,
    sizeSqm: 100,
    pricePerSqm: 56,
    predictedNegotiationReference: 4935,
    predictedNegotiationLow: 4442,
    predictedNegotiationHigh: 5034,
    predictedReviewCategory: "medium-risk",
  },
  {
    id: 15,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 1228,
    sizeSqm: 100,
    pricePerSqm: 12,
    predictedNegotiationReference: 1305,
    predictedNegotiationLow: 1174,
    predictedNegotiationHigh: 1331,
    predictedReviewCategory: "normal",
  },
  {
    id: 16,
    title: "3+ YEARS ON JIJI",
    location: "Bole",
    propertyType: "Property",
    listedPriceUsd: 1053,
    sizeSqm: 130,
    pricePerSqm: 8,
    predictedNegotiationReference: 1895,
    predictedNegotiationLow: 1706,
    predictedNegotiationHigh: 1933,
    predictedReviewCategory: "normal",
  },
  {
    id: 17,
    title: "ETB 190,000 የሚከራይ መጋዘን CMC የተባበሩት አከባቢ Warehouse for Rent Around CMC Addis Ababa Warehouse",
    location: "Bole",
    propertyType: "Commercial",
    listedPriceUsd: 3333,
    sizeSqm: 400,
    pricePerSqm: 8,
    predictedNegotiationReference: 2973,
    predictedNegotiationLow: 2676,
    predictedNegotiationHigh: 3032,
    predictedReviewCategory: "normal",
  },
  {
    id: 18,
    title: "3+ YEARS ON JIJI",
    location: "Akaky Kaliti",
    propertyType: "Property",
    listedPriceUsd: 4211,
    sizeSqm: 500,
    pricePerSqm: 8,
    predictedNegotiationReference: 4543,
    predictedNegotiationLow: 4089,
    predictedNegotiationHigh: 4634,
    predictedReviewCategory: "normal",
  },
  {
    id: 19,
    title: "3+ YEARS ON JIJI",
    location: "Bole",
    propertyType: "Property",
    listedPriceUsd: 5263,
    sizeSqm: 3000,
    pricePerSqm: 1,
    predictedNegotiationReference: 4555,
    predictedNegotiationLow: 4100,
    predictedNegotiationHigh: 4646,
    predictedReviewCategory: "normal",
  },
  {
    id: 20,
    title: "ETB 110,000 Warehouse for Rent in Lafto Area መጋዘን ኪራይ (ሰቶር ኪራይ ) warehouse for rent Total",
    location: "Nifas Silk-Lafto",
    propertyType: "Commercial",
    listedPriceUsd: 1930,
    sizeSqm: 450,
    pricePerSqm: 4,
    predictedNegotiationReference: 1996,
    predictedNegotiationLow: 1796,
    predictedNegotiationHigh: 2036,
    predictedReviewCategory: "normal",
  },
];
