export type PropertyListing = {
  id: number;
  title: string;
  location: string;
  propertyType: string;
  listedPriceUsd: number;
  listedPriceEtb: number;
  sizeSqm: number;
  bedrooms: number;
  bathrooms: number;
  amenitiesCount: number;
  completenessScore: number;
  riskLabel: "normal" | "medium-risk" | "suspicious";
  latitude: number;
  longitude: number;
  status: "verified" | "needs-review" | "flagged";
  description: string;
  imageUrl: string;
  sourcePlatform: string;
  sourceNote: string;
  listingUrl: string;
  verificationStatus: string;
  listingAge: string;
  agentType: string;
};

export const sampleListings: PropertyListing[] = [
  {
    id: 1,
    title: "3+ YEARS ON JIJI",
    location: "Arada",
    propertyType: "Apartment",
    listedPriceUsd: 3158,
    listedPriceEtb: 180000,
    sizeSqm: 100,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 9.035,
    longitude: 38.752,
    status: "verified",
    description: "3+ YEARS ON JIJI",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/11196304_MzAwLTMwMC0yMTUyNGJiYjJk.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/arada/new-builds/diaspora-opportunity-buy-a-luxury-apartment-with-flexible-payment-g64BBUe3iVIGfktYSIDVaVYj.html?page=1&pos=1&cur_pos=1&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=0",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 2,
    title: "ETB 169,000 per month 4bdrm Apartment in Kazanchis, Kirkos for rent Modern, Luxury and Spa",
    location: "Kirkos",
    propertyType: "Apartment",
    listedPriceUsd: 2965,
    listedPriceEtb: 169000,
    sizeSqm: 100,
    bedrooms: 4,
    bathrooms: 4,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 9.0054,
    longitude: 38.7636,
    status: "verified",
    description: "ETB 169,000 per month 4bdrm Apartment in Kazanchis, Kirkos for rent Modern, Luxury and Spa",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/11700978_MzAwLTE1Ny0xYjM1NGE4N2Vj.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/kirkos/houses-apartments-for-rent/4bdrm-apartment-in-kazanchis-kirkos-for-rent-pkK2yU5zeRcVt7SR3QFki2kx.html?page=1&pos=4&cur_pos=4&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=3",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 3,
    title: "3+ YEARS ON JIJI",
    location: "Bole",
    propertyType: "Property",
    listedPriceUsd: 5263,
    listedPriceEtb: 300000,
    sizeSqm: 100,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.9,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/10581336_MzAwLTEzNS1mZjA5MWUwMGFj.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/commercial-property-for-rent/yamikarayi-magzen-92FywrcdxbOmIk6Ddb94cNOo.html?page=1&pos=7&cur_pos=7&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=6",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 4,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 4386,
    listedPriceEtb: 250000,
    sizeSqm: 100,
    bedrooms: 3,
    bathrooms: 3,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI DIAMOND",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/9783715_MzAwLTQwMC0yODIyZTNhNzRm.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/houses-apartments-for-rent/furnished-3bdrm-duplex-in-bole-for-rent-aqomP6XrBhDQQ3FRWllMvkJH.html?page=1&pos=10&cur_pos=10&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=9",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 5,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 1579,
    listedPriceEtb: 90000,
    sizeSqm: 100,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI DIAMOND",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/9850744_MzAwLTIyNS1hOTI0OTAwNmJl.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/houses-apartments-for-rent/furnished-2bdrm-apartment-in-bole-for-rent-6D86ZKFXzknL5b59B0ctjNMI.html?page=1&pos=13&cur_pos=13&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=12",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 6,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 2632,
    listedPriceEtb: 150000,
    sizeSqm: 100,
    bedrooms: 1,
    bathrooms: 1,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI DIAMOND",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/10435500_MzAwLTQwMC0wMjczNzYxYzhm.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/houses-apartments-for-rent/furnished-1bdrm-apartment-in-bole-for-rent-64cddc2VMopc1JJro6057SkX.html?page=1&pos=16&cur_pos=16&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=15",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 7,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 1491,
    listedPriceEtb: 85000,
    sizeSqm: 100,
    bedrooms: 3,
    bathrooms: 3,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI DIAMOND",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/10569277_MzAwLTIyNS00MjMzNzA4YjJh.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/houses-apartments-for-rent/3bdrm-apartment-in-bole-for-rent-oOCP4xbBmTp56hTcKsGTQr0D.html?page=1&pos=19&cur_pos=19&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=18",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 8,
    title: "3+ YEARS ON JIJI",
    location: "Yeka",
    propertyType: "Commercial",
    listedPriceUsd: 2281,
    listedPriceEtb: 130000,
    sizeSqm: 180,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.9,
    riskLabel: "normal",
    latitude: 9.0301,
    longitude: 38.8122,
    status: "verified",
    description: "3+ YEARS ON JIJI",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/4760337_MzAwLTEzNS1kNzNjZWY4OWQw.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/yeka/commercial-property-for-rent/a-warehouse-for-rent-in-the-area-f6dAOeEaEFwWwn3Y8D6pilmx.html?page=1&pos=22&cur_pos=22&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=21",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 9,
    title: "3+ YEARS ON JIJI",
    location: "Akaky Kaliti",
    propertyType: "Commercial",
    listedPriceUsd: 3860,
    listedPriceEtb: 220000,
    sizeSqm: 250,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.9,
    riskLabel: "normal",
    latitude: 8.8767,
    longitude: 38.7894,
    status: "verified",
    description: "3+ YEARS ON JIJI",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/4822984_MzAwLTEzNS03ZjhmMzc1Mjg1.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/akaky-kaliti/commercial-property-for-rent/warehouse-for-rent-in-kaliti-61MjvzTIgMf5FzQ0H30rbXqN.html?page=2&pos=1&cur_pos=1&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=24",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 10,
    title: "ETB 180,000 የሚከራይ መጋዘን አያት አከባቢ በቂ ቢሮ ጋር Warehouse for Rent in Ayat Addis Ababa Warshouse",
    location: "Yeka",
    propertyType: "Commercial",
    listedPriceUsd: 3158,
    listedPriceEtb: 180000,
    sizeSqm: 6000,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 9.0301,
    longitude: 38.8122,
    status: "verified",
    description: "ETB 180,000 የሚከራይ መጋዘን አያት አከባቢ በቂ ቢሮ ጋር Warehouse for Rent in Ayat Addis Ababa Warshouse",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/9050668_MzAwLTE0MC01YzNjZGI4MWFl.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/yeka/commercial-property-for-rent/yamikaraaye-magaazane-ayaate-akabaabi-baqi-biro-gaare-warehouse-for-rent-in-ayat-addis-ababa-2P2UXNbeKpYbmfIQ9cTfCM66.html?page=2&pos=3&cur_pos=3&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=26",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 11,
    title: "ETB 175,000 Warehouse for Rent in Kaliti Aa Warehouse for rent Total area = 700 sq Warehou",
    location: "Akaky Kaliti",
    propertyType: "Commercial",
    listedPriceUsd: 3070,
    listedPriceEtb: 175000,
    sizeSqm: 700,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.8767,
    longitude: 38.7894,
    status: "verified",
    description: "ETB 175,000 Warehouse for Rent in Kaliti Aa Warehouse for rent Total area = 700 sq Warehou",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/7670357_MzAwLTE1OC0zZjRkN2M5NzRlLTE.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/akaky-kaliti/commercial-property-for-rent/warehouse-for-rent-in-kaliti-aa-jRDSL565Br0YeKMPxhNYJo3L.html?page=2&pos=6&cur_pos=6&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=29",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 12,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 2105,
    listedPriceEtb: 120000,
    sizeSqm: 100,
    bedrooms: 3,
    bathrooms: 3,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI DIAMOND",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/9503521_MzAwLTIyNS04Mzc0ZDY3NGEx.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/houses-apartments-for-rent/furnished-3bdrm-apartment-in-bole-for-rent-nGe9nLGUOdEEdw2szd4gwmUn.html?page=2&pos=9&cur_pos=9&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=32",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 13,
    title: "3+ YEARS ON JIJI",
    location: "Akaky Kaliti",
    propertyType: "Property",
    listedPriceUsd: 6667,
    listedPriceEtb: 380000,
    sizeSqm: 100,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.9,
    riskLabel: "normal",
    latitude: 8.8767,
    longitude: 38.7894,
    status: "verified",
    description: "3+ YEARS ON JIJI",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/8181767_MzAwLTEzNS1lY2EwNDQwNjA0.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/akaky-kaliti/commercial-property-for-rent/lakeraaye-yaqaraba-magaazane-nawu-ufstKWyWhfjtpUmoYmACzq3M.html?page=2&pos=11&cur_pos=11&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=34",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 14,
    title: "3+ YEARS ON JIJI",
    location: "Bole",
    propertyType: "Property",
    listedPriceUsd: 5614,
    listedPriceEtb: 320000,
    sizeSqm: 100,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.9,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/6256913_MzAwLTEzNS02NmQ2YzJhZTkw.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/commercial-property-for-rent/yamikaraaye-magaazane-ala-l28UWYDyBVruuuscxL1om8s0.html?page=2&pos=14&cur_pos=14&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=37",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 15,
    title: "3+ YEARS ON JIJI DIAMOND",
    location: "Bole",
    propertyType: "Apartment",
    listedPriceUsd: 1228,
    listedPriceEtb: 70000,
    sizeSqm: 100,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI DIAMOND",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/9428627_MzAwLTQwMC1kZmI3YjY3NDg4.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/houses-apartments-for-rent/2bdrm-apartment-in-chaka-buna-bole-for-rent-19C4pep0XyXOCrSmeedfvyfX.html?page=2&pos=17&cur_pos=17&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=40",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 16,
    title: "3+ YEARS ON JIJI",
    location: "Bole",
    propertyType: "Property",
    listedPriceUsd: 1053,
    listedPriceEtb: 60000,
    sizeSqm: 130,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.9,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/3336248_MzAwLTY2Ny0zNDk3NWI2MmRj.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/commercial-property-for-rent/lakeraaye-qaraba-magaazane-8yKkuoQNeBIvXfb0J5XE2qAQ.html?page=2&pos=20&cur_pos=20&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=43",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 17,
    title: "ETB 190,000 የሚከራይ መጋዘን CMC የተባበሩት አከባቢ Warehouse for Rent Around CMC Addis Ababa Warehouse",
    location: "Bole",
    propertyType: "Commercial",
    listedPriceUsd: 3333,
    listedPriceEtb: 190000,
    sizeSqm: 400,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "ETB 190,000 የሚከራይ መጋዘን CMC የተባበሩት አከባቢ Warehouse for Rent Around CMC Addis Ababa Warehouse",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/8802227_MzAwLTE5OC1lNjZlZTAyOTIx.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/commercial-property-for-rent/yamikaraaye-magaazane-cmc-yatabaabarute-akabaabi-warehouse-for-rent-around-cmc-addis-ababa-fAGmcXZ1P9PQhYWaWJPHVrHp.html?page=3&pos=2&cur_pos=2&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=49",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 18,
    title: "3+ YEARS ON JIJI",
    location: "Akaky Kaliti",
    propertyType: "Property",
    listedPriceUsd: 4211,
    listedPriceEtb: 240000,
    sizeSqm: 500,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.9,
    riskLabel: "normal",
    latitude: 8.8767,
    longitude: 38.7894,
    status: "verified",
    description: "3+ YEARS ON JIJI",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/3702337_MzAwLTEzNS1hMzQzZWY1NmMx.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/akaky-kaliti/commercial-property-for-rent/yemikeryi-megzen-82B2ABKtjRAm2pP0LRkc2WlE.html?page=3&pos=5&cur_pos=5&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=52",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 19,
    title: "3+ YEARS ON JIJI",
    location: "Bole",
    propertyType: "Property",
    listedPriceUsd: 5263,
    listedPriceEtb: 300000,
    sizeSqm: 3000,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.9806,
    longitude: 38.7992,
    status: "verified",
    description: "3+ YEARS ON JIJI",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/3571694_MzAwLTEzNS0wN2E0NWYzZjBh.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/bole/commercial-property-for-rent/ymikerayi-megezen-BQWugQgJdbfsrA6mMnhUiuvi.html?page=3&pos=6&cur_pos=6&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=53",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
  {
    id: 20,
    title: "ETB 110,000 Warehouse for Rent in Lafto Area መጋዘን ኪራይ (ሰቶር ኪራይ ) warehouse for rent Total",
    location: "Nifas Silk-Lafto",
    propertyType: "Commercial",
    listedPriceUsd: 1930,
    listedPriceEtb: 110000,
    sizeSqm: 450,
    bedrooms: 2,
    bathrooms: 2,
    amenitiesCount: 2,
    completenessScore: 0.95,
    riskLabel: "normal",
    latitude: 8.9588,
    longitude: 38.7348,
    status: "verified",
    description: "ETB 110,000 Warehouse for Rent in Lafto Area መጋዘን ኪራይ (ሰቶር ኪራይ ) warehouse for rent Total",
    imageUrl: "https://pictures-ethiopia.jijistatic.com/7670400_MzAwLTExMS0zMjU5ZTM5ZDdhLTE.webp",
    sourcePlatform: "Jiji Ethiopia",
    sourceNote: "Public listing data collected from Jiji Ethiopia for academic MVP demonstration. Private seller details excluded.",
    listingUrl: "https://jiji.com.et/nifas-silk-lafto/commercial-property-for-rent/warehouse-for-rent-in-lafto-area-hSKHZDsTQKSuaSNrirLS7gVN.html?page=3&pos=9&cur_pos=9&ads_per_page=24&ads_count=5181&lid=238FLomGZ_2O8Ekz&indexPosition=56",
    verificationStatus: "Listing details mostly complete",
    listingAge: "Collected for MVP dataset",
    agentType: "Public marketplace listing",
  },
];

export const locations = Array.from(
  new Set(sampleListings.map((listing) => listing.location))
);

export const propertyTypes = Array.from(
  new Set(sampleListings.map((listing) => listing.propertyType))
);

export function getListingsForReview() {
  return sampleListings.filter(
    (listing) => listing.status === "needs-review" || listing.status === "flagged"
  );
}

export function getAveragePriceByLocation(location: string) {
  const listingsInLocation = sampleListings.filter(
    (listing) => listing.location === location
  );

  if (listingsInLocation.length === 0) {
    return 0;
  }

  const total = listingsInLocation.reduce(
    (sum, listing) => sum + listing.listedPriceUsd,
    0
  );

  return Math.round(total / listingsInLocation.length);
}

export function getAveragePricePerSqmByLocation(location: string) {
  const listingsInLocation = sampleListings.filter(
    (listing) => listing.location === location
  );

  if (listingsInLocation.length === 0) {
    return 0;
  }

  const total = listingsInLocation.reduce(
    (sum, listing) => sum + listing.listedPriceUsd / listing.sizeSqm,
    0
  );

  return Math.round(total / listingsInLocation.length);
}
